// src/pages/Profile.tsx
import { useEffect, useState } from 'react';
import { App, Avatar, Button, Descriptions, Form, Input, Modal, Space, Spin } from 'antd';
import { KeyRound, ShieldCheck, UserRound } from 'lucide-react';
import { api, type DataRecord } from '../lib/api';
import { useConsole } from '../lib/console';
import { EnumTag } from '../lib/enums';
import { useSessionQuery, useSessionScope } from '../lib/sessionScope';
import { ErrorState, PageHeader, Panel, RefreshButton } from '../components/ui';
import './admin.css';

export default function Profile() {
  const { t, logout, refreshSession } = useConsole();
  const { message } = App.useApp();
  const scope = useSessionScope();
  const [profileForm] = Form.useForm();
  const [passwordForm] = Form.useForm();
  const [grantForm] = Form.useForm();
  const [saving, setSaving] = useState(false);
  const [changingPassword, setChangingPassword] = useState(false);
  const [granting, setGranting] = useState(false);
  const [passwordOpen, setPasswordOpen] = useState(false);
  const profile = useSessionQuery(scope, () => api.get<DataRecord>('/user/detail', undefined, scope.options));
  useEffect(() => { profileForm.resetFields(); passwordForm.resetFields(); grantForm.resetFields(); setPasswordOpen(false); setSaving(false); setChangingPassword(false); setGranting(false); }, [scope, profileForm, passwordForm, grantForm]);
  const user = profile.data;
  useEffect(() => { if (user) profileForm.setFieldsValue(user); }, [user, profileForm]);
  const saveProfile = async (values: DataRecord) => {
    if (saving || !user || !scope.current()) return;
    setSaving(true);
    try { await api.post('/user/modify', { id: user.id, ...values }, scope.options); if (scope.current()) { void message.success(t('个人信息已保存', 'Profile saved')); await profile.refresh(); if (scope.current()) await refreshSession(); } } catch { /* Leave the submitted values in the form. */ } finally { if (scope.current()) setSaving(false); }
  };
  const changePassword = async (values: DataRecord) => {
    if (changingPassword || !user || !scope.current()) return;
    setChangingPassword(true);
    try { await api.post('/pwjbUser/changePassword', { username: user.originUsername, ...values }, scope.options); if (scope.current()) { void message.success(t('密码已修改，请重新登录', 'Password changed. Please sign in again.')); setPasswordOpen(false); logout(); } } catch { /* Keep the password form open on validation or authentication failure. */ } finally { if (scope.current()) setChangingPassword(false); }
  };
  const grantAdmin = async (values: DataRecord) => {
    if (granting || !scope.current()) return;
    setGranting(true);
    try { await api.post('/appInfo/becomeAdmin', values, scope.options); if (scope.current()) { void message.success(t('已获得应用管理权限', 'Application administrator access granted')); grantForm.resetFields(); await profile.refresh(); } } catch { /* The server owns the grant decision. */ } finally { if (scope.current()) setGranting(false); }
  };
  return <>
    <PageHeader title={t('个人设置', 'Profile')} description={t('维护个人资料、通知方式与访问权限。', 'Manage your profile, notification preferences and access.')} actions={<RefreshButton loading={profile.loading} onClick={() => void profile.refresh()}/>}/>
    <ErrorState error={profile.error} retry={() => void profile.refresh()}/>
    {profile.loading && !user ? <div className="admin-loading"><Spin /></div> : user && <div className="profile-grid">
      <Panel title={t('个人信息', 'Personal information')}>
        <div className="profile-summary"><Avatar size={58} icon={<UserRound size={25}/>} /><div><h2>{user.nick || user.username}</h2><p>{user.username}</p></div><EnumTag kind="accountType" value={user.accountType}/></div>
        <Descriptions size="small" column={1} className="profile-identifiers" items={[
          { key: 'id', label: 'ID', children: String(user.id) },
          { key: 'origin', label: t('原始账号', 'Original account'), children: user.originUsername || '—' },
          { key: 'roles', label: t('全局角色', 'Global roles'), children: (user.globalRoles || []).length ? <Space wrap>{user.globalRoles.map((role: string) => <EnumTag key={role} kind="role" value={role}/>)}</Space> : t('普通用户', 'Member') },
        ]}/>
        <Form name="profile-details" form={profileForm} layout="vertical" className="profile-form" onFinish={saveProfile} disabled={saving}>
          <Form.Item name="nick" label={t('昵称', 'Nickname')}><Input autoComplete="nickname" /></Form.Item>
          <Form.Item name="phone" label={t('手机号', 'Phone number')}><Input autoComplete="tel" /></Form.Item>
          <Form.Item name="email" label={t('邮箱', 'Email')}><Input autoComplete="email" /></Form.Item>
          <Form.Item name="webHook" label={t('通知 Webhook', 'Notification webhook')}><Input placeholder="https://…" /></Form.Item>
          <Space wrap><Button type="primary" htmlType="submit" loading={saving}>{t('保存个人信息', 'Save profile')}</Button>{user.accountType === 'PWJB' && <Button icon={<KeyRound size={15}/>} onClick={() => { passwordForm.resetFields(); setPasswordOpen(true); }}>{t('修改密码', 'Change password')}</Button>}</Space>
        </Form>
      </Panel>
      <div className="profile-secondary">
        <Panel title={t('访问权限', 'Access permissions')}>
          <div className="permission-summary"><ShieldCheck size={20}/><p>{t('以下权限由管理员授予，或通过应用密码验证获取。', 'Access is granted by administrators or by verifying an application password.')}</p></div>
          {['role2NamespaceList', 'role2AppList'].map(key => <section className="permission-list" key={key}><h3>{key === 'role2NamespaceList' ? t('命名空间', 'Namespaces') : t('应用', 'Applications')}</h3>
            {Object.entries(user[key] || {}).some(([, items]) => Array.isArray(items) && items.length) ? Object.entries(user[key] || {}).flatMap(([role, items]) => (items as DataRecord[]).map(item => <div className="permission-item" key={`${role}-${item.id}`}><span>{item.name || item.title || item.appName || item.code}<small>#{item.id}</small></span><EnumTag kind="role" value={role}/></div>)) : <span className="muted">{t('暂无直接授权', 'No direct grants')}</span>}
          </section>)}
        </Panel>
        <Panel title={t('获取应用管理权', 'Claim application access')}>
          <p className="form-section-note">{t('使用应用名称与应用密码，验证后成为该应用管理员。', 'Verify the application code and password to become its administrator.')}</p>
          <Form name="profile-application-access" form={grantForm} layout="vertical" onFinish={grantAdmin} disabled={granting}>
            <Form.Item name="appName" label={t('应用名称', 'Application code')} rules={[{ required: true, message: t('请输入应用名称', 'Enter an application code') }]}><Input /></Form.Item>
            <Form.Item name="password" label={t('应用密码', 'Application password')} rules={[{ required: true, message: t('请输入应用密码', 'Enter an application password') }]}><Input.Password autoComplete="off" /></Form.Item>
            <Button loading={granting} htmlType="submit" icon={<ShieldCheck size={15}/>} block>{t('验证并获取权限', 'Verify and claim access')}</Button>
          </Form>
        </Panel>
      </div>
    </div>}
    <Modal title={t('修改密码', 'Change password')} open={passwordOpen} onCancel={() => { if (!changingPassword) setPasswordOpen(false); }} closable={!changingPassword} mask={{ closable: !changingPassword }} keyboard={!changingPassword} destroyOnHidden footer={<Space><Button disabled={changingPassword} onClick={() => setPasswordOpen(false)}>{t('取消', 'Cancel')}</Button><Button type="primary" loading={changingPassword} onClick={() => passwordForm.submit()}>{t('确认修改', 'Change password')}</Button></Space>}>
      <p className="form-section-note">{t('修改成功后需要重新登录。', 'You will sign in again after changing your password.')}</p>
      <Form name="profile-password" form={passwordForm} layout="vertical" onFinish={changePassword} disabled={changingPassword}>
        <Form.Item label={t('账号', 'Account')}><Input value={user?.originUsername} readOnly /></Form.Item>
        <Form.Item name="oldPassword" label={t('当前密码', 'Current password')}><Input.Password autoComplete="current-password" /></Form.Item>
        <Form.Item name="newPassword" label={t('新密码', 'New password')}><Input.Password autoComplete="new-password" /></Form.Item>
        <Form.Item name="newPassword2" label={t('确认新密码', 'Confirm new password')}><Input.Password autoComplete="new-password" /></Form.Item>
      </Form>
    </Modal>
  </>;
}

// src/features/admin/Profile.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../../core/api'
import { session, signOut } from '../../core/session'
import { clone, t, toast } from '../../core/ui'
import Field from '../../shared/Field.vue'
import Modal from '../../shared/Modal.vue'
import PasswordInput from '../auth/PasswordInput.vue'
import type { Profile } from './contracts'
import { useAdminScope } from './useAdminScope'

const capture = useAdminScope()
const router = useRouter()
const profile = ref<Profile>({ id: '', nick: '', phone: '', email: '', webHook: '' })
const loaded = ref(false)
const loading = ref(false)
const saving = ref(false)
const error = ref('')
const grant = reactive({ appName: '', password: '' })
const granting = ref(false)
const grantError = ref('')
const passwordOpen = ref(false)
const password = reactive({ username: '', oldPassword: '', newPassword: '', newPassword2: '' })
const changing = ref(false)
const passwordError = ref('')
const roleGroups = computed(() => [
  { title: t('命名空间权限', 'Namespace permissions'), roles: profile.value.role2NamespaceList || {}, kind: 'namespace' },
  { title: t('应用权限', 'Application permissions'), roles: profile.value.role2AppList || {}, kind: 'app' },
])
async function load() {
  if (loading.value) return false
  const scope = capture(); loading.value = true; error.value = ''
  try {
    const result = await api<Profile>('/user/detail', { signal: scope.signal, quiet: true })
    if (!scope.valid()) return false
    if (result?.id == null) throw new Error(t('无法读取个人资料，请重试。', 'Your profile could not be loaded. Try again.'))
    profile.value = { ...result, nick: result.nick || '', phone: result.phone || '', email: result.email || '', webHook: result.webHook || '' }; session.user = clone(result); loaded.value = true
    return true
  } catch (failure) { if (scope.valid()) error.value = (failure as Error).message; return false }
  finally { scope.release(); loading.value = false }
}
async function save() {
  if (!loaded.value || loading.value || saving.value) return
  const scope = capture(); saving.value = true; error.value = ''
  const draft = clone(profile.value)
  const body = { id: draft.id, nick: draft.nick || '', phone: draft.phone || '', email: draft.email || '', webHook: draft.webHook || '', extra: draft.extra }
  try {
    await api('/user/modify', { body, signal: scope.signal, quiet: true })
    if (!scope.valid()) return
    const result = await api<Profile>('/user/detail', { signal: scope.signal, quiet: true })
    if (!scope.valid()) return
    if (result?.id == null || !['nick', 'phone', 'email', 'webHook'].every(key => String(result[key as keyof Profile] || '') === String(body[key as keyof typeof body] || ''))) throw new Error(t('服务器未保存全部资料。请检查后重试；当前服务器不支持清空已有字段。', 'The server did not save every field. Review and retry; this server cannot clear existing fields.'))
    profile.value = { ...result, nick: result.nick || '', phone: result.phone || '', email: result.email || '', webHook: result.webHook || '' }; session.user = clone(result)
    toast(t('个人资料已保存', 'Profile saved'), 'success')
  } catch (failure) { if (scope.valid()) { profile.value = draft; error.value = (failure as Error).message } }
  finally { scope.release(); saving.value = false }
}
function openPassword() {
  Object.assign(password, { username: profile.value.originUsername || '', oldPassword: '', newPassword: '', newPassword2: '' }); passwordError.value = ''; passwordOpen.value = true
}
function resetPassword() { Object.assign(password, { username: '', oldPassword: '', newPassword: '', newPassword2: '' }); passwordError.value = '' }
async function changePassword() {
  if (changing.value || !loaded.value || profile.value.accountType !== 'PWJB') return
  if (!password.username || !password.oldPassword || !password.newPassword || !password.newPassword2) { passwordError.value = t('请填写旧密码和两次新密码。', 'Enter your old password and confirm the new password.'); return }
  if (password.newPassword !== password.newPassword2) { passwordError.value = t('两次新密码不一致。', 'The new passwords do not match.'); return }
  const scope = capture(); changing.value = true; passwordError.value = ''
  try {
    await api('/pwjbUser/changePassword', { body: { ...password }, signal: scope.signal, quiet: true })
    if (!scope.valid()) return
    passwordOpen.value = false; resetPassword(); signOut(); toast(t('密码已修改，请重新登录。', 'Password changed. Sign in again.'), 'success'); await router.replace('/loginHomepage')
  } catch (failure) { if (scope.valid()) passwordError.value = (failure as Error).message }
  finally { scope.release(); changing.value = false }
}
async function becomeAdmin() {
  if (granting.value) return
  if (!grant.appName || !grant.password) { grantError.value = t('请填写应用名和应用密码。', 'Enter the application name and password.'); return }
  const scope = capture(); granting.value = true; grantError.value = ''
  try {
    await api('/appInfo/becomeAdmin', { body: { ...grant }, signal: scope.signal, quiet: true })
    if (!scope.valid()) return
    grant.password = ''; toast(t('已获得应用管理权限', 'Application administration granted'), 'success'); await load()
  } catch (failure) { if (scope.valid()) grantError.value = (failure as Error).message }
  finally { scope.release(); granting.value = false }
}
onMounted(() => void load())
</script>

<template>
  <header class="page-head"><div><h1>{{ t('个人中心', 'Profile') }}</h1><p>{{ t('维护联系资料和账号访问权限。', 'Manage your contact details and account access.') }}</p></div></header>
  <div class="profile-layout">
    <section class="work-panel profile-panel" :aria-busy="loading"><div class="profile-heading" data-private><div class="profile-avatar" aria-hidden="true">{{ Array.from(profile.nick || profile.username || 'P')[0]?.toUpperCase() }}</div><div><h2>{{ profile.nick || profile.username || t('个人资料', 'Your profile') }}</h2><p class="muted">{{ profile.accountType || '—' }} · ID {{ profile.id || '—' }}</p></div></div>
      <p v-if="error" class="error-banner" role="alert">{{ error }} <button v-if="!loaded" type="button" class="btn btn-quiet" @click="load">{{ t('重试', 'Retry') }}</button></p><p v-if="loading" class="muted" role="status">{{ t('正在加载…', 'Loading…') }}</p>
      <form @submit.prevent="save"><fieldset class="profile-fields" data-private :disabled="!loaded || loading || saving"><div class="form-grid"><Field :label="t('用户名', 'Username')" v-slot="{ id }"><input :id="id" :value="profile.username" readonly></Field><Field :label="t('原始用户名', 'Original username')" v-slot="{ id }"><input :id="id" :value="profile.originUsername" readonly></Field><Field :label="t('账号类型', 'Account type')" v-slot="{ id }"><input :id="id" :value="profile.accountType" readonly></Field><Field :label="t('全局角色', 'Global roles')" v-slot="{ id }"><input :id="id" :value="profile.globalRoles?.join(', ') || '—'" readonly></Field></div><div class="form-grid contact-fields"><Field :label="t('昵称', 'Nickname')" v-slot="{ id }"><input :id="id" v-model="profile.nick"></Field><Field :label="t('手机号', 'Phone')" v-slot="{ id }"><input :id="id" v-model="profile.phone" type="tel" autocomplete="tel"></Field><Field :label="t('邮箱', 'Email')" v-slot="{ id }"><input :id="id" v-model="profile.email" autocomplete="email"></Field><Field :label="t('Webhook', 'Webhook')" v-slot="{ id }"><input :id="id" v-model="profile.webHook"></Field></div><div class="profile-actions"><button v-if="profile.accountType === 'PWJB'" type="button" class="btn" :disabled="changing" @click="openPassword">{{ t('修改密码', 'Change password') }}</button><button class="btn btn-primary" type="submit">{{ saving ? t('保存中…', 'Saving…') : t('保存资料', 'Save profile') }}</button></div></fieldset></form>
      <details v-if="roleGroups.some(group => Object.keys(group.roles).length)" class="profile-entitlements" data-private><summary>{{ t('查看已有权限', 'View assigned permissions') }}</summary><section v-for="group in roleGroups" :key="group.kind"><h3>{{ group.title }}</h3><div v-for="(targets, role) in group.roles" :key="role" class="entitlement-row"><span class="badge">{{ role }}</span><span>{{ targets.map(target => 'appName' in target ? target.appName : target.showName || target.name || target.code).join(', ') || '—' }}</span></div></section></details>
    </section>
    <aside class="work-panel grant-panel"><h2>{{ t('获取应用管理权限', 'Become an application administrator') }}</h2><p class="muted">{{ t('使用应用名和应用密码获取该应用的管理权限。', 'Use an application name and password to obtain administration access.') }}</p><form @submit.prevent="becomeAdmin"><Field :label="t('应用名', 'Application name')" required v-slot="{ id }"><input :id="id" v-model="grant.appName" required :disabled="granting"></Field><Field :label="t('应用密码', 'Application password')" required v-slot="{ id }"><PasswordInput :id="id" v-model="grant.password" required :disabled="granting" autocomplete="off"/></Field><p v-if="grantError" class="error-banner" role="alert">{{ grantError }}</p><button class="btn btn-primary" type="submit" :disabled="granting">{{ granting ? t('提交中…', 'Submitting…') : t('获取权限', 'Get access') }}</button></form></aside>
  </div>
  <Modal v-model="passwordOpen" :title="t('修改密码', 'Change password')" @closed="resetPassword"><form id="password-form" @submit.prevent="changePassword"><div class="password-fields"><Field :label="t('用户名', 'Username')" v-slot="{ id }"><input :id="id" :value="password.username" readonly autocomplete="username"></Field><Field :label="t('旧密码', 'Old password')" required v-slot="{ id }"><PasswordInput :id="id" v-model="password.oldPassword" :reset-key="passwordOpen" required :disabled="changing"/></Field><Field :label="t('新密码', 'New password')" required v-slot="{ id }"><PasswordInput :id="id" v-model="password.newPassword" :reset-key="passwordOpen" required :disabled="changing" autocomplete="new-password"/></Field><Field :label="t('确认新密码', 'Confirm new password')" required v-slot="{ id }"><PasswordInput :id="id" v-model="password.newPassword2" :reset-key="passwordOpen" required :disabled="changing" autocomplete="new-password"/></Field></div><p v-if="passwordError" class="error-banner" role="alert">{{ passwordError }}</p></form><template #footer><button class="btn btn-quiet" :disabled="changing" @click="passwordOpen = false; resetPassword()">{{ t('取消', 'Cancel') }}</button><button class="btn btn-primary" form="password-form" type="submit" :disabled="changing">{{ changing ? t('提交中…', 'Submitting…') : t('修改密码', 'Change password') }}</button></template></Modal>
</template>

<style scoped>
.profile-layout { display: grid; grid-template-columns: minmax(0,1fr) minmax(280px,.45fr); gap: 20px; align-items: start; }
.profile-panel,.grant-panel { padding: 24px; min-width: 0; }
.profile-heading { display: flex; gap: 13px; align-items: center; margin-bottom: 24px; }
.profile-heading>div { min-width: 0; overflow-wrap: anywhere; }.profile-heading p { font-size: 12px; margin-top: 3px; }
.profile-avatar { display: grid; place-items: center; width: 44px; height: 44px; flex-shrink: 0; border-radius: 13px; background: var(--blue-soft); color: var(--blue); font-size: 20px; font-weight: 750; }
.profile-fields { border: 0; padding: 0; min-width: 0; }.contact-fields { border-top: 1px solid var(--line); margin-top: 22px; padding-top: 22px; }
.profile-actions { display: flex; flex-wrap: wrap; gap: 10px; justify-content: flex-end; margin-top: 22px; }
.grant-panel>p { font-size: 12px; margin: 9px 0 22px; }.grant-panel form,.password-fields { display: grid; gap: 18px; }.grant-panel .btn { justify-self: start; }
.profile-entitlements { margin-top: 24px; border-top: 1px solid var(--line); padding-top: 18px; font-size: 12px; }.profile-entitlements summary { cursor: pointer; font-weight: 650; }.profile-entitlements section { margin-top: 18px; }.entitlement-row { display: flex; gap: 10px; align-items: flex-start; margin-top: 9px; overflow-wrap: anywhere; }.entitlement-row>span:last-child { min-width: 0; }
@media (max-width: 1000px) { .profile-layout { grid-template-columns: 1fr; } }
@media (max-width: 640px) { .profile-panel,.grant-panel { padding: 17px; } }
</style>
